apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: banking
  name: core
spec:
  replicas: 2
  selector:
    matchLabels:
      app: core
  template:
    metadata:
      labels:
        app: core
    spec:
      containers:
        - name: core
          image: banking-core:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          readinessProbe:
            periodSeconds: 5
            httpGet:
              path: /actuator/health/readiness
              port: 8080
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            httpGet:
              path: /actuator/health/liveness
              port: 8080
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  key: DB_URL
                  name: banking-config
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: DB_PORT
                  name: banking-config
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: DB_NAME
                  name: banking-config
            - name: NOTIFICATION_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: NOTIFICATION_SERVICE_URL
                  name: banking-config
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: DB_USERNAME
                  name: banking-secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: banking-secret
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: JWT_SECRET
                  name: banking-secret
