apiVersion: v1
kind: ConfigMap
metadata:
  namespace: banking
  name: banking-config 
data:
  DB_URL: postgres
  DB_PORT: "5432"
  DB_NAME: core_banking
  NOTIFICATION_SERVICE_URL: http://notification:9090
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: guest
  FANOUT_EXCHANGE_NAME: banking.transaction-events
  NOTIFICATION_QUEUE_NAME: notification.transaction-events
  LARGE_AMOUNT_THRESHOLD: "1000000"
  VELOCITY_WINDOW_SECONDS: "60"
  VELOCITY_MAX_COUNT: "5"
  FRAUD_QUEUE_NAME: fraud.transaction-events