apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: banking
  name: fraud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud
  template:
    metadata:
      labels:
        app: fraud
    spec:
      containers:
        - name: fraud
          image: banking-fraud:local
          imagePullPolicy: Never
          ports:
            - containerPort: 9091
          env:
            - name: LARGE_AMOUNT_THRESHOLD
              valueFrom:
                configMapKeyRef:
                  key: LARGE_AMOUNT_THRESHOLD
                  name: banking-config
            - name: VELOCITY_WINDOW_SECONDS
              valueFrom:
                configMapKeyRef:
                  key: VELOCITY_WINDOW_SECONDS
                  name: banking-config
            - name: VELOCITY_MAX_COUNT
              valueFrom:
                configMapKeyRef:
                  key: VELOCITY_MAX_COUNT
                  name: banking-config
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  key: RABBITMQ_HOST
                  name: banking-config
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  key: RABBITMQ_PORT
                  name: banking-config
            - name: RABBITMQ_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: RABBITMQ_USERNAME
                  name: banking-config
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: RABBITMQ_PASSWORD
                  name: banking-secret
            - name: FANOUT_EXCHANGE_NAME
              valueFrom:
                configMapKeyRef:
                  key: FANOUT_EXCHANGE_NAME
                  name: banking-config
            - name: FRAUD_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  key: FRAUD_QUEUE_NAME
                  name: banking-config
          
    
