apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: banking
  name: fx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fx
  template:
    metadata:
      labels:
        app: fx
    spec:
      containers:
        - name: fx
          image: ghcr.io/sinaabdi/fx-service:f3e2de8b4e8ade9e0cffd71d6794cf05587f3a9f
          ports:
            - containerPort: 9092

    