apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: banking
  name: fx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fx
  template:
    metadata:
      labels:
        app: fx
    spec:
      containers:
        - name: fx
          image: ghcr.io/sinaabdi/fx-service:4987b318363465d2b19ffb9612eebbc77582d57a
          ports:
            - containerPort: 9092

    