apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: banking
  name: fx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fx
  template:
    metadata:
      labels:
        app: fx
    spec:
      containers:
        - name: fx
          image: ghcr.io/sinaabdi/fx-service:de7c541434e04664c8f87001f751d6d20152b87d
          ports:
            - containerPort: 9092

    