apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: banking
  name: notification
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: banking-notification:local
          imagePullPolicy: Never
          ports:
            - containerPort: 9090
          env:
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  key: RABBITMQ_HOST
                  name: banking-config
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  key: RABBITMQ_PORT
                  name: banking-config
            - name: RABBITMQ_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: RABBITMQ_USERNAME
                  name: banking-config
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: RABBITMQ_PASSWORD
                  name: banking-secret
            - name: FANOUT_EXCHANGE_NAME
              valueFrom:
                configMapKeyRef:
                  key: FANOUT_EXCHANGE_NAME
                  name: banking-config
            - name: NOTIFICATION_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  key: NOTIFICATION_QUEUE_NAME
                  name: banking-config