apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: banking
  name: reporting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reporting
  template:
    metadata:
      labels:
        app: reporting
    spec:
      containers:
        - name: reporting
          image: ghcr.io/sinaabdi/reporting-service:708d5a09077bd64075ce8763bd29e5c60d9b53fd
          ports:
            - containerPort: 9093
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  key: DB_URL
                  name: banking-config
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: DB_PORT
                  name: banking-config
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: DB_NAME
                  name: banking-config
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: DB_USERNAME
                  name: banking-secret                  
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: banking-secret
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: JWT_SECRET
                  name: banking-secret