spring.application.name=banking

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.datasource.url=jdbc:postgresql://localhost:5432/core_banking
spring.datasource.username=postgres
spring.datasource.password=postgres