spring.application.name=banking

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.datasource.url=jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DB_NAME:core_banking}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

jwt.secret=${JWT_SECRET:7348a4ea07139a02db0cd4934fa960123b70488f2bcc609874f16f59f07aa80c}
jwt.expiration-ms=3600000

management.endpoint.health.probes.enabled=true
management.endpoints.web.exposure.include=health

notification.service.url=${NOTIFICATION_SERVICE_URL:http://localhost:9090}

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

fanout.exchange.name=${FANOUT_EXCHANGE_NAME:banking.transaction-events}