spring.application.name=banking

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.datasource.url=jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DB_NAME:core_banking}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

jwt.sercet=7348a4ea07139a02db0cd4934fa960123b70488f2bcc609874f16f59f07aa80c
jwt.expiration-ms=3600000